/**
 * MyGeotab Objects Constants
 * ===========================
 *
 * Curated list of MyGeotab API objects available for reporting.
 * Source: https://developers.geotab.com/myGeotab/apiReference/objects/
 */

import type { ObjectDefinition, FieldDefinition } from './builder.types';

/**
 * Available MyGeotab objects for reporting
 */
export const MYGEOTAB_OBJECTS: ObjectDefinition[] = [
  // Devices
  {
    type: 'Device',
    category: 'devices',
    label: 'Devices',
    description: 'Physical tracking devices installed in vehicles',
    icon: 'Box',
  },
  {
    type: 'DeviceStatusInfo',
    category: 'devices',
    label: 'Device Status',
    description: 'Current vehicle state including location, speed, and communication status',
    icon: 'Activity',
  },

  // Events & Exceptions
  {
    type: 'ExceptionEvent',
    category: 'events',
    label: 'Exception Events',
    description: 'Events generated by rule violations',
    icon: 'AlertTriangle',
  },
  {
    type: 'FaultData',
    category: 'events',
    label: 'Fault Data',
    description: 'Engine fault codes from vehicle diagnostic systems',
    icon: 'AlertCircle',
  },
  {
    type: 'DutyStatusLog',
    category: 'events',
    label: 'Duty Status',
    description: 'Hours of Service compliance records for drivers',
    icon: 'Clock',
  },

  // Trips & Activities
  {
    type: 'Trip',
    category: 'trips',
    label: 'Trips',
    description: "Vehicle trips and summary of driving activity",
    icon: 'Route',
  },
  {
    type: 'LogRecord',
    category: 'trips',
    label: 'GPS Log Records',
    description: "Device position and speed log entries",
    icon: 'MapPin',
  },
  {
    type: 'ChargeEvent',
    category: 'trips',
    label: 'Charge Events',
    description: 'EV charging locations and consumption details',
    icon: 'Zap',
  },
  {
    type: 'FillUp',
    category: 'trips',
    label: 'Fuel Fill-Ups',
    description: 'Fuel replenishment events',
    icon: 'Fuel',
  },

  // Diagnostics
  {
    type: 'StatusData',
    category: 'events',
    label: 'Status Data',
    description: 'Engine status records representing real-time vehicle parameters',
    icon: 'Gauge',
  },
  {
    type: 'FuelUsed',
    category: 'trips',
    label: 'Fuel Usage',
    description: 'Fuel consumption events for vehicles',
    icon: 'Droplet',
  },
];

/**
 * Field definitions by object type
 * These are common fields - full field list would come from API metadata
 */
export const OBJECT_FIELDS: Record<string, FieldDefinition[]> = {
  Device: [
    { name: 'id', label: 'Device ID', type: 'string', required: true },
    { name: 'name', label: 'Device Name', type: 'string', required: true },
    { name: 'serialNumber', label: 'Serial Number', type: 'string' },
    { name: 'deviceType', label: 'Device Type', type: 'string' },
    { name: 'vehicleIdentificationNumber', label: 'VIN', type: 'string' },
    { name: 'licensePlate', label: 'License Plate', type: 'string' },
    { name: 'comment', label: 'Comment', type: 'string' },
  ],

  DeviceStatusInfo: [
    { name: 'device', label: 'Device', type: 'object', required: true },
    { name: 'latitude', label: 'Latitude', type: 'number' },
    { name: 'longitude', label: 'Longitude', type: 'number' },
    { name: 'speed', label: 'Speed', type: 'number' },
    { name: 'bearing', label: 'Bearing', type: 'number' },
    { name: 'dateTime', label: 'Date/Time', type: 'date' },
    { name: 'currentStateDuration', label: 'Current State Duration', type: 'string' },
  ],

  ExceptionEvent: [
    { name: 'id', label: 'Event ID', type: 'string', required: true },
    { name: 'device', label: 'Device', type: 'object', required: true },
    { name: 'rule', label: 'Rule', type: 'object', required: true },
    { name: 'activeFrom', label: 'Active From', type: 'date', required: true },
    { name: 'activeTo', label: 'Active To', type: 'date' },
    { name: 'state', label: 'State', type: 'string' },
    { name: 'driver', label: 'Driver', type: 'object' },
  ],

  Trip: [
    { name: 'id', label: 'Trip ID', type: 'string', required: true },
    { name: 'device', label: 'Device', type: 'object', required: true },
    { name: 'driver', label: 'Driver', type: 'object' },
    { name: 'start', label: 'Start Time', type: 'date', required: true },
    { name: 'stop', label: 'Stop Time', type: 'date', required: true },
    { name: 'distance', label: 'Distance', type: 'number' },
    { name: 'drivingDuration', label: 'Driving Duration', type: 'string' },
    { name: 'idlingDuration', label: 'Idling Duration', type: 'string' },
    { name: 'maximumSpeed', label: 'Max Speed', type: 'number' },
    { name: 'averageSpeed', label: 'Average Speed', type: 'number' },
  ],

  LogRecord: [
    { name: 'id', label: 'Record ID', type: 'string', required: true },
    { name: 'device', label: 'Device', type: 'object', required: true },
    { name: 'dateTime', label: 'Date/Time', type: 'date', required: true },
    { name: 'latitude', label: 'Latitude', type: 'number' },
    { name: 'longitude', label: 'Longitude', type: 'number' },
    { name: 'speed', label: 'Speed', type: 'number' },
  ],

  FaultData: [
    { name: 'id', label: 'Fault ID', type: 'string', required: true },
    { name: 'device', label: 'Device', type: 'object', required: true },
    { name: 'dateTime', label: 'Date/Time', type: 'date', required: true },
    { name: 'diagnostic', label: 'Diagnostic', type: 'object' },
    { name: 'failureMode', label: 'Failure Mode', type: 'object' },
    { name: 'faultState', label: 'Fault State', type: 'string' },
  ],

  ChargeEvent: [
    { name: 'id', label: 'Charge ID', type: 'string', required: true },
    { name: 'device', label: 'Device', type: 'object', required: true },
    { name: 'startTime', label: 'Start Time', type: 'date', required: true },
    { name: 'endTime', label: 'End Time', type: 'date' },
    { name: 'energyUsed', label: 'Energy Used (kWh)', type: 'number' },
    { name: 'peakPower', label: 'Peak Power (kW)', type: 'number' },
    { name: 'location', label: 'Location', type: 'object' },
  ],

  FillUp: [
    { name: 'id', label: 'Fill-Up ID', type: 'string', required: true },
    { name: 'device', label: 'Device', type: 'object', required: true },
    { name: 'dateTime', label: 'Date/Time', type: 'date', required: true },
    { name: 'volume', label: 'Volume', type: 'number' },
    { name: 'cost', label: 'Cost', type: 'number' },
  ],

  StatusData: [
    { name: 'id', label: 'Status ID', type: 'string', required: true },
    { name: 'device', label: 'Device', type: 'object', required: true },
    { name: 'dateTime', label: 'Date/Time', type: 'date', required: true },
    { name: 'diagnostic', label: 'Diagnostic', type: 'object' },
    { name: 'data', label: 'Data Value', type: 'number' },
  ],

  FuelUsed: [
    { name: 'id', label: 'Fuel ID', type: 'string', required: true },
    { name: 'device', label: 'Device', type: 'object', required: true },
    { name: 'dateTime', label: 'Date/Time', type: 'date', required: true },
    { name: 'volume', label: 'Volume', type: 'number' },
  ],

  DutyStatusLog: [
    { name: 'id', label: 'Log ID', type: 'string', required: true },
    { name: 'driver', label: 'Driver', type: 'object', required: true },
    { name: 'dateTime', label: 'Date/Time', type: 'date', required: true },
    { name: 'status', label: 'Status', type: 'string' },
    { name: 'location', label: 'Location', type: 'object' },
  ],
};

/**
 * Time range presets
 */
export const TIME_RANGE_PRESETS = [
  { value: 'today', label: 'Today' },
  { value: 'yesterday', label: 'Yesterday' },
  { value: 'last7days', label: 'Last 7 Days' },
  { value: 'last30days', label: 'Last 30 Days' },
  { value: 'thisMonth', label: 'This Month' },
  { value: 'lastMonth', label: 'Last Month' },
  { value: 'custom', label: 'Custom Range' },
] as const;
